# Generated by Django 3.1.2 on 2021-12-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
